---
title: "replication_report"
author: "Yari & Kyonne" 
date: "February 22, 2015"
output: html_document
---

Plan for replication project
(1) power analyses - with and without outliers
(2) moderation analysis by gender
(3) graph the results with ggplot2


1: Get data
```{r}
#load packages:
library(pwr)
library(dplyr)
library(plyr)
library(ggplot2)
library(MBESS)
library(psych)
library(car)
library(lsr)

#load data:
dat <- read.csv("GORN_study3.csv", header = TRUE)
dat <-tbl_df(dat)
View(dat)
dat %>%
  filter(na.rm=TRUE) %>%
  group_by(Groep) %>%
  summarise(total.n = n())

by_group<-group_by(dat, Groep)
mutate(distinct_groups= count(n_distinct(Groep))
summarise(distinct_groups)
count(dat, distinct_groups(N()))

#GOT IT TO WORK:
ddply(dat,.(Groep),
      summarise,
      count = length(form_nr1)
      )

#center predictor variable (using blanks for variable name until we get the translated documents:
dat$X.center<-scale(dat$X, center=TRUE, scale=FALSE)

#set moderator as a factor
dat$M<-as.factor(dat$M)

#Test for homogeneity of variance:
leveneTest(dat$X ~ dat$M, center = mean)

#simple effect of centered predictor on Y
model.centered<-lm(dat$______ ~ dat$______.center)
summary(model.centered)

#centered models:
m1.cent<-lm(dat$Y ~ dat$X.center 
            + dat$M)
summary(m1.cent)

m2.cent<-lm(dat$Y ~ dat$X.center 
            + dat$M
            + (dat$X.center*dat$M))
summary(m2.cent)

#compare models
anova(m1.cent, m2.cent)


#Work on tables:
# CODE FOR TABLE HERE:
install.packages("tables")
library(tables)
install.packages("mosaic")
library(mosaic)
install.packages("stargazer")
library(stargazer)
install.packages("xtable")
library(xtable)


# using tables function, doesnt work as planned
csvtable<-tbl_df("Experiment3_ReplicationTable_csv.csv")
view(csvtable)


tabular(dat_egood$music + 1) ~ (n+1) + Format(digits=2)* 
          (dat_egood$chose_advertised_pen)* (n+ proportions), data=dat_egood)))

#not what expected
mosaicplot(freqtable)

# better
attach(dat_egood)
freqtable<-table(dat_egood$music,dat_egood$chose_advertised_pen)
freqtable
margin.table(freqtable, 1)
margin.table(freqtable, 2)
prop.table(freqtable)
proportions <-prop.table(freqtable, 1)
proportions
prop.table(freqtable, 2)

# trying stargazer... no good
stargazer(dat_egood[c("")], type= "text", title= "Frequencies...", digits=2, out="freqtable.txt")

#
tbl2<-tbl_df(tbl2)
print(xtable(tbl2), type="html")
      

```

Graph results of moderation analysis

```{r, echo=FALSE}
##Scatterplots
graph.simple = ggplot(dat, aes(x = wmc.center, y = stroop.rt)) 
graph.simple + geom_smooth(method = "") +
  geom_point() +
  ggtitle("") +
  ylab("") +
  xlab("")

graph.moderator = ggplot(dat, aes(x = X.center, y = Y, colour = M)) 
graph.moderator + geom_smooth(method = "lm") +
  geom_point() +
  ggtitle("") +
  ylab("") +
  xlab("")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
